"""
pages/3_Model_Performance.py — Model Comparison Dashboard
==========================================================
Loads model_metrics.json (generated by train.py) and visualises:
  - Classification: Accuracy, Precision, Recall, F1, ROC-AUC comparison
  - Regression: RMSE, MAE, R², MAPE comparison
  - Best model highlighted
  - MLflow experiment tracking info
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import json, os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

st.set_page_config(page_title="Model Performance | EMIPredict AI", page_icon="📈", layout="wide")
st.title("📈 Model Performance Dashboard")
st.markdown("---")

# ── Load Metrics ───────────────────────────────────────────────────
metrics_path = os.path.join(BASE_DIR, 'models', 'model_metrics.json')
if not os.path.exists(metrics_path):
    st.error("Metrics not found.  Run `python train.py` first.")
    st.stop()

with open(metrics_path) as f:
    metrics = json.load(f)

best_clf = metrics['best_classifier']
best_reg = metrics['best_regressor']

# ══════════════════════════════════════════════════════════════════
# CLASSIFICATION MODELS
# ══════════════════════════════════════════════════════════════════
st.markdown("## 🏷️ Classification Models  *(EMI Eligibility)*")
st.caption("Predicts: Eligible / High_Risk / Not_Eligible")

clf_rows = []
for name, m in metrics['classification'].items():
    clf_rows.append({
        'Model': name,
        'Accuracy':  round(m['val_accuracy'],  4),
        'Precision': round(m['val_precision'], 4),
        'Recall':    round(m['val_recall'],    4),
        'F1 Score':  round(m['val_f1'],        4),
        'ROC-AUC':   round(m['val_roc_auc'],   4),
        'Test Acc':  round(m['test_accuracy'], 4),
        'Best':      '⭐' if name == best_clf else '',
    })

clf_df = pd.DataFrame(clf_rows).sort_values('F1 Score', ascending=False)

# Styled table
st.dataframe(
    clf_df.style.highlight_max(subset=['Accuracy', 'Precision', 'Recall', 'F1 Score', 'ROC-AUC', 'Test Acc'],
                                color='#d4edda'),
    use_container_width=True, hide_index=True
)

# Bar charts
col1, col2 = st.columns(2)
with col1:
    fig = px.bar(clf_df, x='Model', y=['Accuracy', 'F1 Score', 'ROC-AUC'],
                 barmode='group', title="Accuracy / F1 / ROC-AUC Comparison",
                 color_discrete_sequence=px.colors.qualitative.Set2)
    fig.update_xaxes(tickangle=15)
    st.plotly_chart(fig, use_container_width=True)

with col2:
    fig = px.bar(clf_df, x='Model', y=['Precision', 'Recall'],
                 barmode='group', title="Precision vs Recall",
                 color_discrete_sequence=['#636EFA', '#EF553B'])
    fig.update_xaxes(tickangle=15)
    st.plotly_chart(fig, use_container_width=True)

# Radar chart for best model
st.markdown(f"### ⭐ Best Classifier: `{best_clf}`")
best_clf_m = metrics['classification'][best_clf]
radar_categories = ['Accuracy', 'Precision', 'Recall', 'F1', 'ROC-AUC']
radar_values     = [
    best_clf_m['val_accuracy'], best_clf_m['val_precision'],
    best_clf_m['val_recall'],   best_clf_m['val_f1'],
    best_clf_m['val_roc_auc'],
]
radar_values += [radar_values[0]]   # close the polygon
radar_categories += [radar_categories[0]]

fig = go.Figure(go.Scatterpolar(
    r=radar_values, theta=radar_categories,
    fill='toself', name=best_clf,
    line_color='#2ECC71',
))
fig.update_layout(polar=dict(radialaxis=dict(visible=True, range=[0, 1])),
                  title=f"Performance Radar — {best_clf}")
st.plotly_chart(fig, use_container_width=True)

st.markdown("---")

# ══════════════════════════════════════════════════════════════════
# REGRESSION MODELS
# ══════════════════════════════════════════════════════════════════
st.markdown("## 📐 Regression Models  *(Max Monthly EMI)*")
st.caption("Predicts: Maximum safe monthly EMI amount (₹)")

reg_rows = []
for name, m in metrics['regression'].items():
    reg_rows.append({
        'Model':     name,
        'RMSE (₹)':  round(m['val_rmse'],  0),
        'MAE (₹)':   round(m['val_mae'],   0),
        'R²':        round(m['val_r2'],    4),
        'MAPE (%)':  round(m['val_mape'],  2),
        'Test RMSE': round(m['test_rmse'], 0),
        'Best':      '⭐' if name == best_reg else '',
    })

reg_df = pd.DataFrame(reg_rows).sort_values('RMSE (₹)', ascending=True)

st.dataframe(
    reg_df.style.highlight_min(subset=['RMSE (₹)', 'MAE (₹)', 'MAPE (%)'], color='#d4edda')
               .highlight_max(subset=['R²'], color='#d4edda'),
    use_container_width=True, hide_index=True
)

col1, col2 = st.columns(2)
with col1:
    fig = px.bar(reg_df, x='Model', y=['RMSE (₹)', 'MAE (₹)'],
                 barmode='group', title="RMSE vs MAE (lower is better)",
                 color_discrete_sequence=['#EF553B', '#FF7F0E'])
    fig.update_xaxes(tickangle=15)
    st.plotly_chart(fig, use_container_width=True)

with col2:
    fig = px.bar(reg_df, x='Model', y='R²',
                 title="R² Score (higher is better)",
                 color='Model',
                 color_discrete_sequence=px.colors.qualitative.Set2)
    fig.update_xaxes(tickangle=15)
    st.plotly_chart(fig, use_container_width=True)

st.markdown(f"### ⭐ Best Regressor: `{best_reg}`")
best_reg_m = metrics['regression'][best_reg]
c1, c2, c3, c4 = st.columns(4)
c1.metric("RMSE",     f"₹{best_reg_m['val_rmse']:.0f}")
c2.metric("MAE",      f"₹{best_reg_m['val_mae']:.0f}")
c3.metric("R²",       f"{best_reg_m['val_r2']:.4f}")
c4.metric("MAPE",     f"{best_reg_m['val_mape']:.2f}%")

st.markdown("---")

# ── MLflow Info ────────────────────────────────────────────────────
st.markdown("## 🔬 MLflow Experiment Tracking")
st.info("""
All 10 models were logged to MLflow with:
- **Parameters**: model type & hyperparameters
- **Metrics**: accuracy / F1 / ROC-AUC (classification) and RMSE / MAE / R² (regression)
- **Artifacts**: serialised model objects

To launch the MLflow UI locally, run:
```
mlflow ui --backend-store-uri ./mlruns
```
Then open: http://localhost:5000
""")
